"""Backend protocol definitions — all backends implement these interfaces."""

from typing import Protocol, runtime_checkable

from .types import MemoryNode


@runtime_checkable
class TupleSpaceBackend(Protocol):
    """Backend for L2 shared cache (e.g., Redis, NATS KV)."""

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def put(self, key: str, doc: dict, ttl: int | None = None) -> None: ...
    async def get(self, key: str) -> dict | None: ...
    async def delete(self, key: str) -> bool: ...
    async def search(self, index: str, query: str, limit: int = 20) -> list[dict]: ...
    async def atomic_pop(self, index: str, query: str) -> dict | None: ...
    async def keys(self, pattern: str) -> list[str]: ...
    async def create_index(self, name: str, schema: dict) -> None: ...


@runtime_checkable
class MemoryStoreBackend(Protocol):
    """Backend for L3 knowledge graph (e.g., Postgres+AGE+pgvector)."""

    async def connect(self) -> None: ...
    async def close(self) -> None: ...
    async def create_node(self, node: MemoryNode) -> str: ...
    async def get_node(self, node_id: str) -> MemoryNode | None: ...
    async def query_by_tags(self, project: str, tags: list[str], limit: int = 20) -> list[MemoryNode]: ...
    async def query_by_similarity(self, project: str, embedding: list[float], limit: int = 10) -> list[MemoryNode]: ...
    async def create_link(self, from_id: str, to_entity: str, link_type: str, confidence: float = 1.0, reasoning: str | None = None) -> None: ...
    async def get_backlinks(self, entity_name: str, project: str, limit: int = 20) -> list[MemoryNode]: ...
    async def ensure_entity(self, name: str, project: str, entity_type: str | None = None) -> str: ...
    async def get_session_notes(self, session_id: str, project: str, exclude_id: str) -> list[MemoryNode]: ...
    async def increment_access(self, node_id: str) -> None: ...


@runtime_checkable
class EmbeddingProvider(Protocol):
    """Embedding generation (e.g., LiteLLM, OpenAI, local model)."""

    async def embed(self, text: str) -> list[float]: ...

    @property
    def dimensions(self) -> int: ...
